TOP=../..

include $(TOP)/configure/CONFIG

PROD_HOST += ntfieldTest
ntfieldTest_SRCS += ntfieldTest.cpp
ntfieldTest_LIBS += nt pvData Com

PROD_HOST += ntnameValueTest
ntnameValueTest_SRCS += ntnameValueTest.cpp
ntnameValueTest_LIBS += nt pvData Com

PROD_HOST += nttableTest
nttableTest_SRCS += nttableTest.cpp
nttableTest_LIBS += nt pvData Com

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

